[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/deploily-addons
wkhtmltopdf = /usr/local/bin/wkhtmltopdf_utf8.sh
db_host = db
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$x5iTcm6N8X7vfe.99x5D6A$adlzzr2/d7clk23CkEJlvb4Uk2grAMhPHWLD5Wj/hdbTEXWqC2CsfWEaRW2GoU/vjS3v3eMc0FdJJ5OnqA8EHw

