[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/deploily-addons
admin_passwd = $pbkdf2-sha512$600000$ak2pFcJ4j9HaW2vtvRcCoA$BTD0JgntVqT8AaB8sWSPdw3UZ.dGJnqaesrJJ5yPhIZY9qArlh4LykLd1K/R7xOM3gWOYsUU8u9bUZSGSitgjw

