from . import parent
from . import student
from . import course
from . import registration
from . import crm_lead
from . import schedule
from . import test
from . import attendance
from . import hr_extension
from . import ir_http
from . import payment
from . import challenge
from . import session
