{
    'name': 'School Management dz',
    'version': '1.0',
    'category': 'Sales/CRM',
    'summary': 'Custom School Management system with CRM integration',
    'description': "A custom module for managing parents, students, courses, registrations, and integrating with CRM pipeline.",
    'author': 'Your Company',
    'depends': ['base', 'crm', 'website', 'portal', 'hr', 'hr_recruitment'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/crm_stages.xml',
        'data/mock_data.xml',
        'views/parent_views.xml',
        'views/attendance_views.xml',
        'views/student_views.xml',
        'views/course_views.xml',
        'views/registration_views.xml',
        'views/test_views.xml',
        'views/crm_views.xml',
        'views/menus.xml',
        'views/hr_extension_views.xml',
        'views/website_templates.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
